//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScoreMvc.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMvcSchoolEntities : DbContext
    {
        public DBMvcSchoolEntities()
            : base("name=DBMvcSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCLUBS> TBLCLUBS { get; set; }
        public virtual DbSet<TBLCOURSES> TBLCOURSES { get; set; }
        public virtual DbSet<TBLSCORES> TBLSCORES { get; set; }
        public virtual DbSet<TBLSTUDENTS> TBLSTUDENTS { get; set; }
    }
}
