//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScoreMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCOURSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCOURSES()
        {
            this.TBLSCORES = new HashSet<TBLSCORES>();
        }
    
        public byte COURSEID { get; set; }
        public string COURSENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSCORES> TBLSCORES { get; set; }
    }
}
