//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScoreMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSCORES
    {
        public int SCOREID { get; set; }
        public byte COURSEID { get; set; }
        public Nullable<int> STUID { get; set; }
        public Nullable<byte> EXAM1 { get; set; }
        public Nullable<byte> EXAM2 { get; set; }
        public Nullable<byte> EXAM3 { get; set; }
        public Nullable<byte> PROJECT { get; set; }
        public Nullable<decimal> MEAN { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLCOURSES TBLCOURSES { get; set; }
        public virtual TBLSTUDENTS TBLSTUDENTS { get; set; }
    }
}
