//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScoreMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSTUDENTS()
        {
            this.TBLSCORES = new HashSet<TBLSCORES>();
        }
    
        public int STUID { get; set; }
        public string STUNAME { get; set; }
        public string STUSURNAME { get; set; }
        public string STUPHOTO { get; set; }
        public string STUGENDER { get; set; }
        public Nullable<byte> STUCLUB { get; set; }
    
        public virtual TBLCLUBS TBLCLUBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSCORES> TBLSCORES { get; set; }
    }
}
